name: sip-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - mkl
  - fortran-magic
  # - gcc
  - pip:
    - pymatsolver
    # - git+https://github.com/simpeg/simpegEM1D.git@master

