name: sip-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - mkl
  # - gcc
  - pip:
    - h5py
    - git+https://github.com/simpeg/simpeg.git@spectral-ip-addition
    - git+https://github.com/simpeg/simpegEM1D.git@global_dualmoment
