name: sip-environment

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - scipy
  - matplotlib
  - mkl
  - h5py
  - fortran-compiler
  - pip:
    - pymatsolver
    - git+https://github.com/simpeg/simpegEM1D.git@global_dualmoment
    - git+https://github.com/simpeg/simpeg.git@spectral-ip-addition
